default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
development:
  <<: *default
  database: calender-sync

test:
  <<: *default
  database: calender-sync-test

production:
  <<: *default
  database:
  username: calender-sync-pros
  password: <%= ENV["PROD_DATABASE_PASSWORD"] %>